### ISSUE TITLE
null is not an object  ( evaluating 'ZiggeoRecorder.rearCamera') 

### ISSUE THREAD

**Issue by vijaysinghrajput** [Ziggeo/ReactNativeSDK#32]
This Error show  while integration

**Comment by 3akat** [comment]
Hi @vijaysinghrajput, 
is it on iOs or Android? or both?

**Comment by vijaysinghrajput** [comment]
Right Now I am using Android . WHEN I initialized this npm with all code .and refresh it  show error null is not an object ( evaluating 'ZiggeoRecorder.rearCamera')

**Comment by vijaysinghrajput** [comment]
Thank You for your response

I have a website which are using Ziggeo .
and I am Developing App by Expo Show this error occur.


my 2nd question is -
Can I send Video to Ziggeo Databse by using Custom Video recorder??

**Comment by 3akat** [comment]
If I understand correctly you're trying to use the SDK with Expo (https://expo.io), am I right?

**Comment by vijaysinghrajput** [comment]
yes i want use expo

**Comment by vijaysinghrajput** [comment]
i want to  use in expo

**Comment by vijaysinghrajput** [comment]
Yes i want use in expo 
i Tried to do this :   Usage with Expo #30
but not got solution

**Comment by 3akat** [comment]
Roger, will check today

**Comment by 3akat** [comment]
okay, I didn't find any issue, so, let's start from the beginning. 
Do you have `android` and `ios` folders in your expo project?

**Comment by vijaysinghrajput** [comment]
No I dont have these folder . I did not eject it .

**Comment by 3akat** [comment]
If you don't have `android` and `ios` folders that means you didn't use `bare` mode in Expo, our SDK currently works with Expo only in `bare` mode.  The thread you've mentioned (#30) is the correct one for searching the solution.  

In short:
 - if you have existing expo project you can follow this https://docs.expo.io/versions/v28.0.0/expokit/detach/
 - if you want to create a proj from scratch, you can use the following command   
`expo init --template bare-minimum`
 - if you want to play with simple ReactNative project without Expo, you can take a look at the Demo we have here   
https://github.com/Ziggeo/ReactNativeDemo

**Comment by jcharbo** [comment]
This library still does not work with React Native 60+ without Expo.  I can get past the above error by creating a podspec file for the library but the ziggeo library headers and then not found.

**Comment by bansal84k** [comment]
@jcharbo We have taken note of the issue and our Dev team is checking it out. We have also logged a ticket in our system with all the details so that it is easier to collect any further information and follow up the issue in the correct platform/team. If you wish to continue here, its fine, however it will be easier to keep track as a separate issue related to iOS, since this thread originally detailed the issue on Android.

**Comment by yaronlevi** [comment]
I am seeing the same issue on iOS only (on android it works fine!)
I've created a fresh React Native project with version 0.61.5
This is a full React Native project (**not Expo**).

I followed the steps from the docs:

1) npm install react-native-ziggeo-library --save
2) react-native link
3) Add the Ziggeo.framework file to the Xcode project.

But when running the project I am getting this error.

So Ziggeo's React Native SDK does not support iOS on 0.61.5?

**Comment by Bane-D** [comment]
Hi Yaron,

Could you please write on this post instead: https://github.com/Ziggeo/ReactNativeSDK/issues/35 It is for iOS and non Expo so it matches your case.

It should work however by re-opening that one we could focus better on it since _this_ thread is originally opened for Android and was fixed, and the one above #35 is for iOS so would help avoid confusion.

Thank you :)
